// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJfIehCHQC2rZq3bsYEum___KhZ83kxYw',
    appId: '1:478717586065:android:d7d413a2fc4674b8e3ed30',
    messagingSenderId: '478717586065',
    projectId: 'shatarko',
    databaseURL: 'https://shatarko-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shatarko.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6M20MvlOQCdrzkkwfWOzdUlbrcCp6sGw',
    appId: '1:478717586065:ios:02ddbdd6a4828085e3ed30',
    messagingSenderId: '478717586065',
    projectId: 'shatarko',
    databaseURL: 'https://shatarko-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shatarko.appspot.com',
    iosClientId: '478717586065-86cmceuolef2utm492r679q5sk2jul44.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotification',
  );
}
